### ISSUE TITLE
Missing DB settings cause errors.

### ISSUE THREAD

**Issue by haydn** [rahult/karo#7]
If you're database.yml file is missing the `host` file:

``` yml
development:
  adapter: mysql2
  database: example
  # host: localhost
  password: example
  username: example
```

Running `karo db pull` causes errors when it tries to run:

```
mysql -v -h -C -uexample -pexample example
```
